### PR TITLE
Add support for a 'revid' parameter on notifyCommit

### PR DESCRIPTION
**Pull request by sthenault**
It may be used to specify the changeset identifer to use for a build.

### CODE REVIEW

**Comment by jglick** [comment]
I can see how this works, but as a rule I am leery of features “inspired by” the bloated and undertested Git plugin. :-) What is the real motivation here, given that the Mercurial plugin (intentionally) disallows building branch wildcards (you should use `branch-api` plugin integrations instead)? In other words, given that a given project will always be building a specific branch, what is the benefit of building something other than the latest commit on that branch as of the start of the build?

Potentially to ensure that every commit gets individually tested, even if they arrive in rapid succession and the queue cannot keep up; but this relies on the webhook being reliably notified in every case (which will not happen if, say, Jenkins is being restarted at the wrong moment). So then you need to verify that a regular polling fallback (`@daily` or whatever) will always ensure that the tip of the branch got built, even if a directly submitted revision was built since the last time polling ran. Probably the current patch does satisfy that condition but it is not tested.

**Comment by sthenault** [comment]
The main problem I'm willing to  fix here is that with (our usage of) mercurial, one may push several heads at once. In such case, jenkins does only launch a build for one head among other. Using the notifyCommit API with revid support, we can control which changeset will trigger a build *in the commit hook* that will notify jenkins and so do whatever we want at this level (notify on one head, all heads, all csets, etc).

I've to admit I've not thought that much about the potential connection problem during notification, but I don't think this is a big deal (for us, at least).

I don't know if this kind of thing may be handled by the branch-api-plugin, and the documentation is rather sparse (https://wiki.jenkins-ci.org/display/JENKINS/Branch+API+Plugin)

**Comment by sthenault** [comment]
ping? Any update on this?

**Comment by sthenault** [comment]
more ping?

**Comment by jglick** [comment]
Generally this sort of thing is better handled by multibranch projects. Branch indexing finds new and removed branches, and finds new commits on all live branches, and schedules appropriate builds.

**Comment by dlax** [comment]
Does a multibranch project make it possible to trigger builds on new commits that would appear on distinct heads of a given branch?

Say you have the following history:
```
o  changeset: c03c7758d909
|  summary:   update release notes
|  branch:    default
|  phase:     draft
|
o  changeset: c288c285280f
|  summary:   new feature
|  branch:    default
|  phase:     draft
|
| o  changeset: 156bf0839120
|/   summary:   fix something
|    branch:    default
|    phase:     draft
|
o  changeset: 4cc3efa963e5
   summary:   release v1.0
   branch:    default
   phase:     public
```
And changesets `156bf0839120` and `c288c285280f::c03c7758d909` (which address completely different things, so should not be on the same history line, but both concerns the `default` branch)  get pushed within a short time frame while Jenkins is not ready to process both as quick as would be needed. What would happen then is that, two builds will be put in queue but both would checkout `tip` of the remote repository (here changeset `c03c7758d909`) and changeset `156bf0839120` will never get tested.

This kind of workflow where a given branch has several heads *in draft phase* makes it possible for multiple developers to work on the same branch while not cluttering the history with Mercurial *named branches* used as *topic branches* (à la git).

So back on the example above, the repository receiving changes would send `notifyCommit=156bf0839120` and `notifyCommit=c03c7758d909` to Jenkins and, hopefully, the builds queued will use that to test the requested changesets whatever the `tip` of the configured branch is.

**Comment by jglick** [comment]
> Does a multibranch project make it possible to trigger builds on new commits that would appear on distinct heads of a given branch?

Not currently. A fairly marginal use case not supported at the moment. It _could_ be supported, in which case no change to `notifyCommit` would be needed.

**Comment by jglick** [comment]
Superseded by #92.

**Pull request closed without merging**
