### PR TITLE
catch AbortException for hg locate, add '--hidden' for certain commands and add option to include bookmarks

### PR DESCRIPTION
**Pull request by domruf**

### CODE REVIEW

**Comment by domruf** [comment]
@stephenc what version of mercurial is used for these tests? What is the oldest supported version that I need to consider?

**Comment by jglick** [comment]
> what version of mercurial is used for these tests?

Pretty much up in the air until I find time to fix up and merge #93.

**Comment by jglick** [comment]
The first sounds related to #106.

**Comment by tlvu** [comment]
@domruf Using Mercurial Evolve with Jenkins here.

You should also add --hidden for hg status.

Otherwise we have this error:
```
ERROR: Failed to run /opt/mercurial/bin/hh status --rev bfa9618dd315285b6001ef04998ff52f963ce8c4 --rev 919545acca1af54b5dce7bffbbc04f62dae91598
abort: hidden revision 'bfa9618dd315285b6001ef04998ff52f963ce8c4'!
(use --hidden to access hidden revisions)
ERROR: polling failed in /var/jenkins_home/jobs/BC-Services/jobs/bc-protos-devel-default/workspace@script on : null
```

for commit hook build trigger on a single branch pipeline.  Weirdly enough, multi branch pipeline commit hook build trigger works fine and simply ignore this error.

Thanks for adding Evolve support to Jenkins.

**Comment by jglick** [comment]
Closing this as it seems abandoned, though there are likely pieces that could be resurrected.

@tlvu I have not used Mercurial in years and have no idea what Evolve is or what `--hidden` does. If you think you know of a code change which would fix some scenario you encounter, please file a separate PR covering just that change, with a functional test demonstrating the need for it if at all possible (I can give some pointers in a new PR upon request).

**Pull request closed without merging**
