### PR TITLE
[FIXED JENKINS-30120] Fix extra changes being found

### PR DESCRIPTION
**Pull request by xavierzwirtz**
The current revset query used to grab changes grabs extra changes on large repositories with odd graphs. On our repository with 20000+ commits it is registering 10000+ changes everytime it builds.

I believe this is due to a bug in the revset query used to grab changes. Consider the following graph:

```
@  changeset:   5:2dccdf4acafc
|  branch:      b1
|  tag:         tip
|  parent:      3:c1c5663af0b7
|  summary:     wolo2
|
| o  changeset:   4:939721587c26
| |  branch:      b2
| |  parent:      1:1fd80701afc5
| |  summary:     wolo
| |
o |  changeset:   3:c1c5663af0b7
| |  branch:      b1
| |  summary:     frobnosticate
| |
o |  changeset:   2:a78553b9c3ae
|/    summary:     foobarbaz
|
o  changeset:   1:1fd80701afc5
|  summary:     foobar
|
o  changeset:   0:600d548d0dcb
   summary:     Init
```

This graph is "odd" because rev 3 is a parent of rev 4. Which means when the existing change detection
code runs, it registers 4 as a change:

```
$ hg log --prune a78553b9c3ae --rev '2dccdf4acafc:0' --template '{rev}:{node}\n'
5:2dccdf4acafc73146eac9ba994bcac99105c4a83
4:939721587c260401d99cb598e97b4b4a533698d8
3:c1c5663af0b791671f24ab441da839d836847e4e
```

On this small repository, its not that big of a deal. We get an extra change in the change log, but thats it. On our main very large repository we have started running out of memory during change detection. It also takes roughly 15 minutes to detect changes.

In my experimentation running using `ancestors('$BRANCH_NAME') and not ancestors($LAST_CHANGE_ID)` as the revset and dropping `--prune` will give the intended results.

### CODE REVIEW

**Comment by jglick** [comment]
Seems like it should be straightforward to write a functional test demonstrating this, no?

**Comment by jglick** [comment]
And it looks like this would supersede #69?

**Comment by xavierzwirtz** [comment]
Yes, it does contain #69 as well. Looking into writing a functional test for this. Don't have tons of experience with java.

**Comment by jglick** [comment]
Understood. I would like to be able to spend some time on this, but I am pretty overloaded and the Mercurial plugin is kind of a side project for me.

**Comment by datallah** [comment]
I've reviewed and tested these changes, and it works well.

It would be nice to get this merged and released!

**Comment by bguerin** [comment]
any chance to get this merged and included in a release ?
the changelog is just unusable at this time in production ...

**Comment by harcher81** [comment]
Thanks you for this fix, it works.

This fix is absolutly required if you activate the caches or sharing options (without theses options, only the needed branch is retrieved and we don't have the problem).

**Comment by xavierzwirtz** [comment]
Yup, we use sharing, which is what caused the issue for us. We have been using this in production since I pushed the bug fix, has worked great.

**Comment by xavierzwirtz** [comment]
We were actually killing the Jenkins process because so much data was returned by mercurial that it caused the process to run out of memory.

**Comment by jglick** [comment]
Probably breaks people using older versions of Mercurial. However people using newer versions need to be the first priority. Making the plugin support _any_ version is impractical given the current test harness, which assumes `hg` in `$PATH`. See comment in #69 for suggestions on fixing this situation. At the moment I cannot spare the time to work on the plugin so I just need to trust based on comments that this is a safe fix.

**Comment by xavierzwirtz** [comment]
Thanks for merging @jglick.

**Comment by jglick** [comment]
Working on publishing 1.55.

**Pull request merged**
